CREATE TABLE [User]
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	UserFio NVARCHAR(255) NULL,
	UserBirthday DATE NULL,
	UserEmail NVARCHAR(255) NOT NULL,
	UserPassword NVARCHAR(MAX) NOT NULL,
	UserPhone NVARCHAR(30) NULL,
	UserRole NVARCHAR(20) DEFAULT 'Пользователь'
)

CREATE TABLE Cart
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	UserId INT NOT NULL
)

CREATE TABLE CartGood
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CartId INT NOT NULL,
	GoodId INT NOT NULL,
	GoodAmount INT DEFAULT 1
)

CREATE TABLE Good
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NameGood NVARCHAR(255) NOT NULL,
	DescriptionGood TEXT NOT NULL,
	GoodPrice INT NOT NULL CHECK (GoodPrice <= 100000),
	GoodImage TEXT,
	GoodCount INT NOT NULL CHECK (GoodCount >= 0),
	TypeId INT NOT NULL,
	BrandId INT NOT NULL
)

CREATE TABLE [Type]
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TypeName NVARCHAR(255) NOT NULL
)

CREATE TABLE Brand
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	BrandName NVARCHAR(255) NOT NULL
)

CREATE TABLE ShopGood
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ShopId INT NOT NULL,
	GoodId INT NOT NULL
)

CREATE TABLE Shop
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ShopName NVARCHAR(255) NOT NULL,
	ShopAddress NVARCHAR(255) NOT NULL,
	ShopPhone NVARCHAR(30) NOT NULL
)

CREATE TABLE OrderGood
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	OrderId INT NOT NULL,
	GoodId INT NOT NULL
)

CREATE TABLE [Order]
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	OrderDate DATETIME DEFAULT GETDATE(),
	OrderPrice INT NOT NULL,
	UserId INT NOT NULL
)