ALTER TABLE [Order]
ADD CONSTRAINT FK_ORDER_USER
FOREIGN KEY (UserId)
REFERENCES [User](Id)
ON DELETE CASCADE

ALTER TABLE Cart
ADD CONSTRAINT FK_CART_USER
FOREIGN KEY (UserId)
REFERENCES [User](Id)
ON DELETE CASCADE

ALTER TABLE CartGood
ADD CONSTRAINT FK_CART_GOOD_CART
FOREIGN KEY (CartId)
REFERENCES Cart(Id)
ON DELETE CASCADE

ALTER TABLE CartGood
ADD CONSTRAINT FK_CART_GOOD_GOOD
FOREIGN KEY (GoodId)
REFERENCES Good(Id)
ON DELETE CASCADE

ALTER TABLE Good
ADD CONSTRAINT FK_GOOD_TYPE
FOREIGN KEY (TypeId)
REFERENCES [Type](Id)
ON DELETE CASCADE

ALTER TABLE Good
ADD CONSTRAINT FK_GOOD_BRAND
FOREIGN KEY (BrandId)
REFERENCES Brand(Id)
ON DELETE CASCADE

ALTER TABLE ShopGood
ADD CONSTRAINT FK_SHOP_GOOD_GOOD
FOREIGN KEY (GoodId)
REFERENCES Good(Id)
ON DELETE CASCADE

ALTER TABLE ShopGood
ADD CONSTRAINT FK_SHOP_GOOD_SHOP
FOREIGN KEY (ShopId)
REFERENCES Shop(Id)
ON DELETE CASCADE

ALTER TABLE OrderGood
ADD CONSTRAINT FK_ORDER_GOOD_ORDER
FOREIGN KEY (OrderId)
REFERENCES [Order](Id)
ON DELETE CASCADE

ALTER TABLE OrderGood
ADD CONSTRAINT FK_ORDER_GOOD_GOOD
FOREIGN KEY (GoodId)
REFERENCES Good(Id)
ON DELETE CASCADE